# Data Preparation & Quality Assessment

## Project

AI-Powered Factory Reallocation & Shipping Optimization Recommendation System

### Milestone

Week 1 • Milestone 2 • Day 2

---

## Objective

The objective of this notebook is to perform a comprehensive assessment of the Nassau Candy Distributor dataset before any preprocessing or modeling begins.

This notebook focuses on understanding the dataset structure, evaluating data quality, validating business rules, identifying inconsistencies, and defining an appropriate data cleaning strategy.

The insights gathered here will form the foundation for all subsequent stages including exploratory data analysis, feature engineering, machine learning, and factory optimization.

## Business Context

Nassau Candy Distributor currently relies on static factory assignments for product distribution.

Before building predictive models or recommendation systems, it is essential to ensure that the historical operational data is accurate, complete, and suitable for analysis.

Poor data quality can lead to incorrect business insights and unreliable optimization recommendations.

Therefore, this notebook performs a detailed data quality audit to evaluate the integrity of the dataset and identify any preprocessing requirements.

In [23]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import plotly.express as px

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 10)
pd.set_option("display.max_colwidth", None)

print("Libraries imported successfully.")

Libraries imported successfully.

In [24]:
from pathlib import Path

data_path = Path("../data/raw")

csv_file = list(data_path.glob("*.csv"))[0]

print(csv_file)

df = pd.read_csv(csv_file)

print("Dataset loaded successfully!")

..\data\raw\Nassau Candy Distributor (1).csv
Dataset loaded successfully!

In [25]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [26]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
10189,10190,US-2024-143259-CHO-MIL-31000,30-12-2025,26-06-2030,Standard Class,143259,United States,New York City,New York,10009,Chocolate,Atlantic,CHO-MIL-31000,Wonka Bar - Milk Chocolate,9.75,3,6.33,3.42
10190,10191,US-2024-115427-CHO-NUT-13000,30-12-2025,26-06-2030,Standard Class,115427,United States,Fairfield,California,94533,Chocolate,Pacific,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,6.98,2,4.98,2.00
10191,10192,US-2024-156720-CHO-SCR-58000,30-12-2025,26-06-2030,Standard Class,156720,United States,Loveland,Colorado,80538,Chocolate,Pacific,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
10192,10193,US-2024-143259-CHO-TRI-54000,30-12-2025,26-06-2030,Standard Class,143259,United States,New York City,New York,10009,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,26.25,7,17.15,9.10
10193,10194,CA-2024-143500-CHO-SCR-58000,30-12-2025,26-06-2030,Standard Class,143500,Canada,Charlottetown,Prince Edward Island,C0A,Chocolate,Atlantic,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30

In [27]:
df.sample(5, random_state=42)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
6636,6637,US-2023-108777-CHO-FUD-51000,12-12-2025,03-06-2029,Same Day,108777,United States,Lorain,Ohio,44052,Chocolate,Atlantic,CHO-FUD-51000,Wonka Bar - Fudge Mallows,10.80,3,7.20,3.6
3742,3743,US-2022-102778-CHO-TRI-54000,21-11-2024,16-05-2028,First Class,102778,United States,Monroe,North Carolina,28110,Chocolate,Gulf,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,3.75,1,2.45,1.3
5114,5115,US-2023-153577-CHO-TRI-54000,27-06-2025,21-12-2028,Standard Class,153577,United States,Highland Park,Illinois,60035,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.9
6505,6506,US-2023-161025-CHO-FUD-51000,03-12-2025,31-05-2029,Standard Class,161025,United States,Los Angeles,California,90049,Chocolate,Pacific,CHO-FUD-51000,Wonka Bar - Fudge Mallows,14.40,4,9.60,4.8
10072,10073,US-2024-155376-CHO-SCR-58000,22-12-2025,19-06-2030,Standard Class,155376,United States,Independence,Missouri,64055,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.3

### Observation

The dataset contains order-level transactional records.

Each row represents a customer order containing customer information,
product details, shipping information and financial metrics.

Random sampling confirms that the data appears consistent and no
obvious formatting issues are visible at first glance.

In [28]:
rows, cols = df.shape

print("="*45)
print("DATASET DIMENSIONS")
print("="*45)
print(f"Rows    : {rows:,}")
print(f"Columns : {cols}")

=============================================
DATASET DIMENSIONS
=============================================
Rows    : 10,194
Columns : 18

### Observation

Understanding the size of the dataset provides an estimate of the
available information for analysis and machine learning.

The dataset contains sufficient observations to support exploratory
analysis and predictive modeling.

In [29]:
for i, column in enumerate(df.columns, start=1):
    print(f"{i:2}.{column}")

 1.Row ID
 2.Order ID
 3.Order Date
 4.Ship Date
 5.Ship Mode
 6.Customer ID
 7.Country/Region
 8.City
 9.State/Province
10.Postal Code
11.Division
12.Region
13.Product ID
14.Product Name
15.Sales
16.Units
17.Gross Profit
18.Cost

In [30]:
len(df.columns)

18

### Observation

The dataset contains attributes related to:

- Order Information
- Customer Information
- Geographic Information
- Product Information
- Shipping Details
- Financial Metrics

These variables collectively provide the necessary information for
building a shipping optimization recommendation system.

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  str
 3   Ship Date       10194 non-null  str
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  str
 7   City            10194 non-null  str
 8   State/Province  10194 non-null  str
 9   Postal Code     10194 non-null  str
 10  Division        10194 non-null  str
 11  Region          10194 non-null  str
 12  Product ID      10194 non-null  str
 13  Product Name    10194 non-null  str
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), str(12)
memory usage: 2.9 MB

In [32]:
df.dtypes

Row ID            int64
Order ID            str
Order Date          str
Ship Date           str
Ship Mode           str
                 ...
Product Name        str
Sales           float64
Units             int64
Gross Profit    float64
Cost            float64
Length: 18, dtype: object

### Observation

The data type inspection identifies columns that require conversion,
particularly date fields.

Correct data types are essential for accurate feature engineering and
subsequent predictive modeling.

In [33]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Row ID,10194.0,5097.500000,2942.898656,1.00,2549.25,5097.50,7645.75,10194.0
Customer ID,10194.0,134468.961154,20231.483007,100006.00,117212.00,133550.00,152051.00,192314.0
Sales,10194.0,13.908537,11.341020,1.25,7.20,10.80,18.00,260.0
Units,10194.0,3.791838,2.228317,1.00,2.00,3.00,5.00,14.0
Gross Profit,10194.0,9.166451,6.643740,0.25,4.90,7.47,12.25,130.0
Cost,10194.0,4.742087,5.061647,0.60,2.40,3.60,5.70,130.0

In [34]:
df.describe(include="object").T

                count unique                           top  freq
Order ID        10194   8549  US-2021-155502-CHO-MIL-31000     5
Order Date      10194    717                    02-09-2025    62
Ship Date       10194   1338                    07-06-2028    38
Ship Mode       10194      4                Standard Class  6120
Country/Region  10194      2                 United States  9994
...               ...    ...                           ...   ...
Postal Code     10194    654                         10035   263
Division        10194      3                     Chocolate  9844
Region          10194      4                       Pacific  3253
Product ID      10194     15                 CHO-MIL-31000  2137
Product Name    10194     15    Wonka Bar - Milk Chocolate  2137

[12 rows x 4 columns]

### Observation

The descriptive statistics provide an overview of the numerical
distribution and categorical diversity within the dataset.

This step also helps identify unusual values that may require
further investigation during data cleaning.

In [35]:
memory = df.memory_usage(deep=True).sum() / (1024**2)

print("="*45)
print("MEMORY USAGE")
print("="*45)
print(f"{memory:.2f} MB")

=============================================
MEMORY USAGE
=============================================
2.90 MB

In [22]:
missing = (
    df.isnull()
    .sum()
    .to_frame(name="Missing Values")
)

missing["Percentage"] = (
    missing["Missing Values"] / len(df) * 100
)

missing

              Missing Values  Percentage
Row ID                     0         0.0
Order ID                   0         0.0
Order Date                 0         0.0
Ship Date                  0         0.0
Ship Mode                  0         0.0
...                      ...         ...
Product Name               0         0.0
Sales                      0         0.0
Units                      0         0.0
Gross Profit               0         0.0
Cost                       0         0.0

[18 rows x 2 columns]

In [36]:
missing[missing["Missing Values"] > 0]

Empty DataFrame
Columns: [Missing Values, Percentage]
Index: []

### Observation

No missing values were detected in the dataset.

This indicates that the dataset is complete and does not require missing-value imputation before further analysis.

In [37]:
duplicates = df.duplicated().sum()

print(f"Duplicate Rows : {duplicates}")

Duplicate Rows : 0

### Observation

Duplicate rows are evaluated because repeated transactions may bias analytical results and machine learning models.

Only true duplicate records should be removed.

In [38]:
duplicate_orders = (
    df["Order ID"]
    .duplicated()
    .sum()
)

print(duplicate_orders)

1645

In [39]:
df["Order ID"].value_counts().head(10)

Order ID
US-2021-155502-CHO-MIL-31000    5
US-2022-112130-CHO-FUD-51000    5
US-2022-126977-CHO-SCR-58000    5
US-2022-130974-CHO-SCR-58000    5
US-2024-113278-CHO-MIL-31000    5
US-2024-104731-CHO-FUD-51000    5
US-2024-157987-CHO-NUT-13000    5
US-2024-100111-CHO-NUT-13000    5
US-2021-167927-CHO-FUD-51000    4
US-2021-140858-CHO-MIL-31000    4
Name: count, dtype: int64

### Observation

Multiple records per Order ID are expected because a single customer order may contain multiple products.

Therefore, repeated Order IDs do not necessarily indicate duplicate transactions.

In [40]:
for column in df.columns:

    print("="*50)
    print(column)
    print("="*50)

    print(df[column].nunique())

==================================================
Row ID
==================================================
10194
==================================================
Order ID
==================================================
8549
==================================================
Order Date
==================================================
717
==================================================
Ship Date
==================================================
1338
==================================================
Ship Mode
==================================================
4
==================================================
Customer ID
==================================================
5044
==================================================
Country/Region
==================================================
2
==================================================
City
==================================================
542
==================================================
State/Province
==================================================
59
==================================================
Postal Code
==================================================
654
==================================================
Division
==================================================
3
==================================================
Region
==================================================
4
==================================================
Product ID
==================================================
15
==================================================
Product Name
==================================================
15
==================================================
Sales
==================================================
88
==================================================
Units
==================================================
14
==================================================
Gross Profit
==================================================
121
==================================================
Cost
==================================================
95

In [53]:
unique_summary = pd.DataFrame({
    "Column": df.columns,
    "Unique Values": df.nunique().values,
    "Data Type": df.dtypes.values
})

unique_summary.sort_values("Unique Values")

            Column  Unique Values Data Type
6   Country/Region              2       str
10        Division              3       str
11          Region              4       str
4        Ship Mode              4       str
15           Units             14     int64
..             ...            ...       ...
2       Order Date            717       str
3        Ship Date           1338       str
5      Customer ID           5044     int64
1         Order ID           8549       str
0           Row ID          10194     int64

[18 rows x 3 columns]

In [46]:
print(f"Negative Sales Records : {(df['Sales'] < 0).sum()}")
print(f"Negative Cost Records  : {(df['Cost'] < 0).sum()}")
print(f"Negative Profit Records: {(df['Gross Profit'] < 0).sum()}")
print(f"Zero Unit Orders       : {(df['Units'] == 0).sum()}")

Negative Sales Records : 0
Negative Cost Records  : 0
Negative Profit Records: 0
Zero Unit Orders       : 0

### Observation

Financial variables are validated to ensure that no impossible business transactions exist.

Negative sales, zero-unit orders, or invalid costs may indicate data quality issues requiring further investigation.

In [56]:
df["Order Date"] = pd.to_datetime(df["Order Date"], format="mixed")

df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="mixed")

In [57]:
df[["Order Date","Ship Date"]].dtypes

Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

### Observation

Order Date and Ship Date have been converted into datetime format.

This enables time-based analysis, feature engineering, and shipping lead-time calculations.

In [58]:
df["Shipping Lead Time"] = (
    df["Ship Date"] -  df["Order Date"]
).dt.days

In [59]:
df["Shipping Lead Time"].describe()

count    10194.000000
mean      1344.239356
std        294.675072
min        491.000000
25%       1194.000000
50%       1276.000000
75%       1638.000000
max       1965.000000
Name: Shipping Lead Time, dtype: float64

In [60]:
df[["Order Date",
    "Ship Date",
    "Shipping Lead Time" 
]].head()

  Order Date  Ship Date  Shipping Lead Time
0 2024-03-01 2026-06-30                 851
1 2024-04-01 2026-01-07                 646
2 2024-04-01 2026-01-07                 646
3 2024-04-01 2026-01-07                 646
4 2024-05-01 2026-05-07                 736

In [61]:
invalid_dates = (
    df["Shipping Lead Time"] < 0
).sum()

print(f"Invalid Shipping Records : {invalid_dates}")

Invalid Shipping Records : 0

### Observation

Shipping lead time must always be zero or greater.

Negative values indicate invalid business records that require investigation.

# Data Cleaning Strategy

Based on the quality assessment, the following preprocessing steps will be performed in the next phase.

## Completed

- Dataset successfully imported
- Data structure validated
- Missing values assessed
- Duplicate records checked
- Financial variables validated
- Unique categorical values reviewed
- Date columns converted

## Planned Cleaning

- Create Shipping Lead Time feature
- Extract Year, Month, Quarter
- Validate shipping duration
- Encode categorical variables
- Detect statistical outliers
- Prepare modeling dataset

## Conclusion

The dataset demonstrates excellent overall quality with no missing values,
duplicate records, or invalid financial transactions.

Only minor preprocessing and feature engineering are required before
exploratory data analysis.